CREATE DATABASE UkraineEvents;
USE UkraineEvents;
CREATE TABLE Events (
    data_id INT,
    iso INT,
    event_id_cnty VARCHAR(255),
    event_id_no_cnty INT,
    event_date DATE,
    year INT,
    time_precision INT,
    event_type VARCHAR(255),
    sub_event_type VARCHAR(255),
    actor1 VARCHAR(255),
    assoc_actor_1 VARCHAR(255),
    inter1 INT,
    actor2 VARCHAR(255),
    assoc_actor_2 VARCHAR(255),
    inter2 INT,
    interaction INT,
    region VARCHAR(255),
    country VARCHAR(255),
    admin1 VARCHAR(255),
    admin2 VARCHAR(255),
    admin3 VARCHAR(255),
    location VARCHAR(255),
    latitude FLOAT,
    longitude FLOAT,
    geo_precision INT,
    source VARCHAR(255),
    source_scale VARCHAR(255),
    notes TEXT,
    fatalities INT,
    timestamp INT,
    iso3 VARCHAR(3),
    PRIMARY KEY (data_id)
);